/* tslint:disable */
/* eslint-disable */
/**
 * Advertisement service
 * Advertisement open api docs
 *
 * The version of the OpenAPI document: 2.14.0-dev.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AdvertisementBaseDto
 */
export interface AdvertisementBaseDto {
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  dtoName: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  origin: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  project: string;
  /**
   *
   * @type {Array<string>}
   * @memberof AdvertisementBaseDto
   */
  projects: Array<string>;
  /**
   *
   * @type {Array<object>}
   * @memberof AdvertisementBaseDto
   */
  extra?: Array<object>;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  category: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  state?: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  businessState?: number;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  updatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  imageId?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof AdvertisementBaseDto
   */
  imageIds?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  userId?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof AdvertisementBaseDto
   */
  userIds?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  locationId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof AdvertisementBaseDto
   */
  locationIds?: Array<string>;
  /**
   *
   * @type {object}
   * @memberof AdvertisementBaseDto
   */
  geoPoint?: object;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  parentId?: string;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  unitPrice?: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  transaction: number;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  description: string;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  price?: number;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  internalNoteToPrice?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  internalNote?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  publishUp?: string;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  availability?: number;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  externalId?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  publishDown?: string;
  /**
   *
   * @type {boolean}
   * @memberof AdvertisementBaseDto
   */
  top?: boolean;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  topTo?: string;
  /**
   *
   * @type {boolean}
   * @memberof AdvertisementBaseDto
   */
  highlight?: boolean;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  highlightTo?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof AdvertisementBaseDto
   */
  videoUrl?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof AdvertisementBaseDto
   */
  fileIds?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  priceLocal?: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  priceCurrent?: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  unitPriceLocal?: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  unitPriceCurrent?: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  quantity?: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  userSubjectType?: number;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sourceId?: string;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  sourceType?: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  photosCount?: number;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  topFrom?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  highlightFrom?: string;
  /**
   *
   * @type {Array<number>}
   * @memberof AdvertisementBaseDto
   */
  categoriesAll?: Array<number>;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  updatedBy?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  street?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sourceImportId?: string;
  /**
   *
   * @type {Array<number>}
   * @memberof AdvertisementBaseDto
   */
  categoriesSecondary?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof AdvertisementBaseDto
   */
  validationState?: Array<number>;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  clientCreatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  clientUpdatedAt?: string;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  unitPriceFrom?: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  unitPriceTo?: number;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sortPublish?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sortTop?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sortHighlight?: string;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  finalPrice?: number;
  /**
   *
   * @type {Array<number>}
   * @memberof AdvertisementBaseDto
   */
  tags?: Array<number>;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  note?: string;
  /**
   *
   * @type {boolean}
   * @memberof AdvertisementBaseDto
   */
  premium?: boolean;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  premiumFrom?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  premiumTo?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sortPremium?: string;
  /**
   *
   * @type {Array<number>}
   * @memberof AdvertisementBaseDto
   */
  userSubjectTypes?: Array<number>;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  scoreQuality?: number;
  /**
   *
   * @type {boolean}
   * @memberof AdvertisementBaseDto
   */
  advertiserIsOwner?: boolean;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  forSale?: number;
  /**
   *
   * @type {number}
   * @memberof AdvertisementBaseDto
   */
  scoreQualityPercent?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof AdvertisementBaseDto
   */
  wasPublished?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  finalPriceDate?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof AdvertisementBaseDto
   */
  parentIds?: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof AdvertisementBaseDto
   */
  colored?: boolean;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  coloredFrom?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  coloredTo?: string;
  /**
   *
   * @type {boolean}
   * @memberof AdvertisementBaseDto
   */
  sticker1?: boolean;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sticker1From?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sticker1To?: string;
  /**
   *
   * @type {boolean}
   * @memberof AdvertisementBaseDto
   */
  sticker2?: boolean;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sticker2From?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sticker2To?: string;
  /**
   *
   * @type {boolean}
   * @memberof AdvertisementBaseDto
   */
  redTop?: boolean;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  redTopFrom?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  redTopTo?: string;
  /**
   *
   * @type {string}
   * @memberof AdvertisementBaseDto
   */
  sortRedTop?: string;
}
